# Generated by Django 3.0.5 on 2020-05-07 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200506_0752'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_offset', models.IntegerField()),
                ('led_offset', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PrintingState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('ready', 'ready'), ('print', 'print'), ('pause', 'pause')], default='ready', max_length=6)),
                ('total_layer', models.IntegerField()),
                ('current_layer', models.IntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='post.Material')),
            ],
        ),
    ]
