# Generated by Django 3.0.5 on 2020-05-07 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_printersetting_printingstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printingstate',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='post.Material'),
        ),
    ]
