# Generated by Django 3.0.5 on 2020-05-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20200507_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printingstate',
            name='current_layer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='printingstate',
            name='total_layer',
            field=models.IntegerField(default=0),
        ),
    ]
