# Generated by Django 3.0.5 on 2020-05-08 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20200507_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printingstate',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='post.Material'),
        ),
    ]
