# Generated by Django 3.0.5 on 2020-05-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20200511_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='layer_height',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
