# Generated by Django 3.0.5 on 2020-05-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_printingstate_printing_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printingstate',
            name='printing_name',
            field=models.CharField(blank=True, default='-', max_length=50, null=True),
        ),
    ]
