# Generated by Django 3.0.5 on 2020-05-14 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20200512_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printingstate',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.Material'),
        ),
    ]
