# Generated by Django 3.0.5 on 2020-05-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20200514_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printingstate',
            name='state',
            field=models.CharField(choices=[('ready', 'ready'), ('print', 'print'), ('pause', 'pause'), ('SETTING', 'setting')], default='ready', max_length=7),
        ),
    ]
