# Generated by Django 3.0.5 on 2020-05-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20200514_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='printingstate',
            name='print_setting_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
