# Generated by Django 3.0.5 on 2020-05-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_printingstate_print_setting_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='layer_height',
        ),
        migrations.AddField(
            model_name='material',
            name='down_accel_speed',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='down_decel_speed',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='init_speed',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='max_speed',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='up_accel_speed',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='up_decel_speed',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
