# Generated by Django 3.0.5 on 2020-05-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_auto_20200522_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printingstate',
            name='printing_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
