# Generated by Django 3.0.5 on 2020-05-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_auto_20200525_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='printingstate',
            name='print_setting_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
