# Generated by Django 3.0.5 on 2020-05-30 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_printingstate_print_setting_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printingstate',
            name='print_setting_time',
        ),
        migrations.AddField(
            model_name='printingstate',
            name='printing_file_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
