# Generated by Django 3.0.7 on 2020-07-28 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_auto_20200530_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printingstate',
            old_name='printing_file_name',
            new_name='printing_folder_name',
        ),
    ]
