# Generated by Django 3.0.5 on 2020-07-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_auto_20200530_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printingstate',
            name='material',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
