# Generated by Django 3.0.5 on 2020-07-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_auto_20200728_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printingstate',
            name='state',
            field=models.CharField(choices=[('ready', 'ready'), ('print', 'print'), ('pause', 'pause'), ('setting', 'setting')], default='ready', max_length=11),
        ),
    ]
