# Generated by Django 3.0.7 on 2020-08-04 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_auto_20200728_1807'),
        ('post', '0022_auto_20200728_0033'),
    ]

    operations = [
    ]
