# Generated by Django 3.0.7 on 2020-08-05 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0023_merge_20200804_0039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilePrinting',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PrinterSetting',
        ),
        migrations.DeleteModel(
            name='PrintingState',
        ),
    ]
